### ISSUE TITLE
Deployed app fails

### ISSUE THREAD

**Issue by wooorm** [eltongonc/real-time_web#1]
http://eltongoncalves.com/minor/

Shows the following error:

```
Not Found 404 Error: Not Found at /home/elton/portfolio/app.js:46:15 at Layer.handle [as handle_request] (/home/elton/portfolio/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/home/elton/portfolio/node_modules/express/lib/router/index.js:317:13) at /home/elton/portfolio/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/home/elton/portfolio/node_modules/express/lib/router/index.js:335:12) at next (/home/elton/portfolio/node_modules/express/lib/router/index.js:275:10) at /home/elton/portfolio/node_modules/express/lib/router/index.js:635:15 at next (/home/elton/portfolio/node_modules/express/lib/router/index.js:260:14) at Function.handle (/home/elton/portfolio/node_modules/express/lib/router/index.js:174:3) at router (/home/elton/portfolio/node_modules/express/lib/router/index.js:47:12)
```

**Comment by eltongonc** [comment]
Aah snap! Wrong link. http://real-time-web.herokuapp.com is the correct one.
